In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../Data/all_clean.csv")
data

,Unnamed: 0,text,sp500_mean_label,sp500_last_label,usdx_mean_label,usdx_last_label
0,0,new semester start corporate finance valuation...,1,1.0,1,1.0
1,1,google valuable apple depend value measure fir...,0,1.0,0,1.0
2,2,fall valuation class start sept welcome websit...,0,0.0,0,0.0
3,3,assume tesla grow audi like revenue b porsche ...,1,1.0,1,1.0
4,4,twitter s value company bargain b fair deal b ...,0,0.0,0,0.0
...,...,...,...,...,...,...
6657,6657,yield german government bond reaction news gov...,0,0.0,0,0.0
6658,6658,fed funds go + stop people buy foot animatroni...,0,0.0,0,0.0
6659,6659,wonderful spend day lauderinstitute wharton pe...,0,0.0,0,0.0
6660,6660,need say european government invest infrastruc...,0,0.0,0,0.0
6661,6661,birth year man olympics basketball team head c...,0,0.0,0,0.0

In [1]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

words = " "
stopwords = list(STOPWORDS) + ["t","co", "https", "number", "email"]

for string in data.text:
    tokens = string.split()

    for i in range(len(tokens)):
        tokens[i] = tokens[i].lower()
    tokens = set(tokens)
    words += " ".join(tokens)+ " "

wordcloud = WordCloud(width = 1600, height = 800,
            background_color ="white",
            stopwords = stopwords,
            min_font_size = 15).generate(words)

plt.figure(figsize = (8, 8), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad = 0)
plt.savefig('wordcloud.png')
plt.show()

ModuleNotFoundError: No module named 'wordcloud'